// Generated by Haxe 3.4.4

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.unit {
	public class TestStatus : global::haxe.lang.HxObject {
		
		public TestStatus(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public TestStatus() {
			global::haxe.unit.TestStatus.__hx_ctor_haxe_unit_TestStatus(this);
		}
		
		
		public static void __hx_ctor_haxe_unit_TestStatus(global::haxe.unit.TestStatus __hx_this) {
			__hx_this.done = false;
			__hx_this.success = false;
		}
		
		
		public bool done;
		
		public bool success;
		
		public string error;
		
		public string method;
		
		public string classname;
		
		public object posInfos;
		
		public string backtrace;
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1512997393:
					{
						this.posInfos = ((object) (@value) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1604552446:
					{
						this.backtrace = global::haxe.lang.Runtime.toString(@value);
						return @value;
					}
					
					
					case 1512997393:
					{
						this.posInfos = ((object) (@value) );
						return @value;
					}
					
					
					case 1902405251:
					{
						this.classname = global::haxe.lang.Runtime.toString(@value);
						return @value;
					}
					
					
					case 156956385:
					{
						this.method = global::haxe.lang.Runtime.toString(@value);
						return @value;
					}
					
					
					case 1932118984:
					{
						this.error = global::haxe.lang.Runtime.toString(@value);
						return @value;
					}
					
					
					case 944645571:
					{
						this.success = global::haxe.lang.Runtime.toBool(@value);
						return @value;
					}
					
					
					case 1114501250:
					{
						this.done = global::haxe.lang.Runtime.toBool(@value);
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1604552446:
					{
						return this.backtrace;
					}
					
					
					case 1512997393:
					{
						return this.posInfos;
					}
					
					
					case 1902405251:
					{
						return this.classname;
					}
					
					
					case 156956385:
					{
						return this.method;
					}
					
					
					case 1932118984:
					{
						return this.error;
					}
					
					
					case 944645571:
					{
						return this.success;
					}
					
					
					case 1114501250:
					{
						return this.done;
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1512997393:
					{
						return ((double) (global::haxe.lang.Runtime.toDouble(this.posInfos)) );
					}
					
					
					default:
					{
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override void __hx_getFields(global::Array<object> baseArr) {
			baseArr.push("backtrace");
			baseArr.push("posInfos");
			baseArr.push("classname");
			baseArr.push("method");
			baseArr.push("error");
			baseArr.push("success");
			baseArr.push("done");
			base.__hx_getFields(baseArr);
		}
		
		
	}
}


