// Generated by Haxe 3.4.4

#pragma warning disable 109, 114, 219, 429, 168, 162
public class Etudiant : global::haxe.lang.HxObject {
	
	public Etudiant(global::haxe.lang.EmptyObject empty) {
	}
	
	
	public Etudiant(string n, string p) {
		global::Etudiant.__hx_ctor__Etudiant(this, n, p);
	}
	
	
	public static void __hx_ctor__Etudiant(global::Etudiant __hx_this, string n, string p) {
		__hx_this.nom = n;
		__hx_this.prenom = p;
	}
	
	
	public string nom;
	
	public string prenom;
	
	public string classe;
	
	public virtual string getNom() {
		return this.nom;
	}
	
	
	public virtual string getPrenom() {
		return this.prenom;
	}
	
	
	public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
		unchecked {
			switch (hash) {
				case 84982061:
				{
					this.classe = global::haxe.lang.Runtime.toString(@value);
					return @value;
				}
				
				
				case 784134345:
				{
					this.prenom = global::haxe.lang.Runtime.toString(@value);
					return @value;
				}
				
				
				case 5495052:
				{
					this.nom = global::haxe.lang.Runtime.toString(@value);
					return @value;
				}
				
				
				default:
				{
					return base.__hx_setField(field, hash, @value, handleProperties);
				}
				
			}
			
		}
	}
	
	
	public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
		unchecked {
			switch (hash) {
				case 722696703:
				{
					return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "getPrenom", 722696703)) );
				}
				
				
				case 589500950:
				{
					return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "getNom", 589500950)) );
				}
				
				
				case 84982061:
				{
					return this.classe;
				}
				
				
				case 784134345:
				{
					return this.prenom;
				}
				
				
				case 5495052:
				{
					return this.nom;
				}
				
				
				default:
				{
					return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
				}
				
			}
			
		}
	}
	
	
	public override object __hx_invokeField(string field, int hash, global::Array dynargs) {
		unchecked {
			switch (hash) {
				case 722696703:
				{
					return this.getPrenom();
				}
				
				
				case 589500950:
				{
					return this.getNom();
				}
				
				
				default:
				{
					return base.__hx_invokeField(field, hash, dynargs);
				}
				
			}
			
		}
	}
	
	
	public override void __hx_getFields(global::Array<object> baseArr) {
		baseArr.push("classe");
		baseArr.push("prenom");
		baseArr.push("nom");
		base.__hx_getFields(baseArr);
	}
	
	
}


