// Generated by Haxe 3.4.4

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe {
	public class StackItem : global::haxe.lang.ParamEnum {
		
		public StackItem(int index, object[] @params) : base(index, @params) {
		}
		
		
		public static readonly string[] __hx_constructs = new string[]{"CFunction", "Module", "FilePos", "Method", "LocalFunction"};
		
		public static readonly global::haxe.StackItem CFunction = new global::haxe.StackItem(0, null);
		
		public static global::haxe.StackItem Module(string m) {
			unchecked {
				return new global::haxe.StackItem(1, new object[]{m});
			}
		}
		
		
		public static global::haxe.StackItem FilePos(global::haxe.StackItem s, string file, int line) {
			unchecked {
				return new global::haxe.StackItem(2, new object[]{s, file, line});
			}
		}
		
		
		public static global::haxe.StackItem Method(string classname, string method) {
			unchecked {
				return new global::haxe.StackItem(3, new object[]{classname, method});
			}
		}
		
		
		public static global::haxe.StackItem LocalFunction(global::haxe.lang.Null<int> v) {
			unchecked {
				return new global::haxe.StackItem(4, new object[]{(v).toDynamic()});
			}
		}
		
		
		public override string getTag() {
			return global::haxe.StackItem.__hx_constructs[this.index];
		}
		
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe {
	public class CallStack : global::haxe.lang.HxObject {
		
		public CallStack(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public CallStack() {
			global::haxe.CallStack.__hx_ctor_haxe_CallStack(this);
		}
		
		
		public static void __hx_ctor_haxe_CallStack(global::haxe.CallStack __hx_this) {
		}
		
		
		public static global::Array<object> exceptionStack() {
			return global::haxe.CallStack.makeStack(new global::System.Diagnostics.StackTrace(((global::System.Exception) (global::haxe.lang.Exceptions.exception) ), ((bool) (true) )));
		}
		
		
		public static string toString(global::Array<object> stack) {
			global::StringBuf b = new global::StringBuf();
			{
				int _g = 0;
				while (( _g < stack.length )) {
					global::haxe.StackItem s = ((global::haxe.StackItem) (stack[_g]) );
					 ++ _g;
					b.b.Append(((string) ("\nCalled from ") ));
					global::haxe.CallStack.itemToString(b, s);
				}
				
			}
			
			return b.b.ToString();
		}
		
		
		public static void itemToString(global::StringBuf b, global::haxe.StackItem s) {
			unchecked {
				switch (s.index) {
					case 0:
					{
						b.b.Append(((string) ("a C function") ));
						break;
					}
					
					
					case 1:
					{
						string m = global::haxe.lang.Runtime.toString(s.@params[0]);
						{
							b.b.Append(((string) ("module ") ));
							b.b.Append(((string) (global::Std.@string(m)) ));
						}
						
						break;
					}
					
					
					case 2:
					{
						int line = ((int) (global::haxe.lang.Runtime.toInt(s.@params[2])) );
						string file = global::haxe.lang.Runtime.toString(s.@params[1]);
						global::haxe.StackItem s1 = ((global::haxe.StackItem) (s.@params[0]) );
						{
							if (( s1 != null )) {
								global::haxe.CallStack.itemToString(b, s1);
								b.b.Append(((string) (" (") ));
							}
							
							b.b.Append(((string) (global::Std.@string(file)) ));
							b.b.Append(((string) (" line ") ));
							b.b.Append(((string) (global::Std.@string(line)) ));
							if (( s1 != null )) {
								b.b.Append(((string) (")") ));
							}
							
						}
						
						break;
					}
					
					
					case 3:
					{
						string meth = global::haxe.lang.Runtime.toString(s.@params[1]);
						string cname = global::haxe.lang.Runtime.toString(s.@params[0]);
						{
							b.b.Append(((string) (global::Std.@string(cname)) ));
							b.b.Append(((string) (".") ));
							b.b.Append(((string) (global::Std.@string(meth)) ));
						}
						
						break;
					}
					
					
					case 4:
					{
						global::haxe.lang.Null<int> n = global::haxe.lang.Null<object>.ofDynamic<int>(s.@params[0]);
						{
							b.b.Append(((string) ("local function #") ));
							b.b.Append(((string) (global::Std.@string((n).toDynamic())) ));
						}
						
						break;
					}
					
					
				}
				
			}
		}
		
		
		public static global::Array<object> makeStack(global::System.Diagnostics.StackTrace s) {
			global::Array<object> stack = new global::Array<object>(new object[]{});
			{
				int _g1 = 0;
				int _g = s.FrameCount;
				while (( _g1 < _g )) {
					int i = _g1++;
					global::System.Diagnostics.StackFrame frame = s.GetFrame(((int) (i) ));
					global::System.Reflection.MethodBase m = frame.GetMethod();
					if (( m == null )) {
						continue;
					}
					
					global::haxe.StackItem method = global::haxe.StackItem.Method(( ( m as global::System.Reflection.MemberInfo ).ReflectedType as global::System.Reflection.MemberInfo ).ToString(), ( m as global::System.Reflection.MemberInfo ).Name);
					string fileName = frame.GetFileName();
					int lineNumber = frame.GetFileLineNumber();
					if ((  ! (string.Equals(fileName, null))  || ( lineNumber >= 0 ) )) {
						stack.push(global::haxe.StackItem.FilePos(method, fileName, lineNumber));
					}
					else {
						stack.push(method);
					}
					
				}
				
			}
			
			return stack;
		}
		
		
	}
}


